version: '3'

services:
  nginx_server:
    container_name: Nginx
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile-nginx
    ports:
      - "8081:80"
    volumes:
      - ./dist/:/usr/share/nginx/html/

  apache2_server:
    container_name: Apache2
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile-apache2
    ports:
      - "8082:80"
    volumes:
      - ./dist/:/usr/local/apache2/htdocs/